# Generated by Django 5.2.4 on 2025-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vcffile",
            name="subscription_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="vcffile",
            name="unlimited_contacts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vcffile",
            name="vcf_type",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vcffile",
            name="max_contacts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
