# Generated by Django 5.2.4 on 2025-08-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_contact_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vcffile',
            index=models.Index(fields=['hidden', 'vcf_type'], name='vcf_hidden_type_idx'),
        ),
        migrations.AddIndex(
            model_name='vcffile',
            index=models.Index(fields=['-created_at'], name='vcf_created_at_idx'),
        ),
    ]
