# Generated by Django 5.2.4 on 2025-07-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vcf_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('max_contacts', models.PositiveIntegerField(blank=True, null=True)),
                ('unlimited_contacts', models.BooleanField(default=False)),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('vcf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vcfviewer.vcffile')),
            ],
            options={
                'unique_together': {('vcf_file', 'phone')},
            },
        ),
    ]
