# Generated by Django 5.2.4 on 2025-07-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcfviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('vcf_file', 'phone')},
        ),
    ]
