# Generated by Django 5.2.4 on 2025-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='include_email_in_vcf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
