# Generated by Django 5.2.4 on 2025-08-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='authentication_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
