# Generated by Django 5.2.4 on 2025-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='is_email_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
