# Generated by Django 5.2.4 on 2025-08-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_emailverificationotp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Verification OTP', 'verbose_name_plural': 'Email Verification OTPs'},
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='authentication_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Authentication Email'),
        ),
    ]
