# Generated by Django 5.2.4 on 2025-08-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_emailverificationotp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='auth_email_last_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Authentication Email Change'),
        ),
    ]
