# Generated by Django 5.2.4 on 2025-08-13 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberaccount_auth_email_last_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstNameLastName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_last_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
