# Generated by Django 5.2.4 on 2025-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_firstnamelastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
