# Generated by Django 5.2.4 on 2025-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_memberprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
