# Generated by Django 5.2.4 on 2025-08-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_vcffile_vcf_hidden_type_idx_and_more'),
        ('members', '0010_memberprofile_about_me_memberprofile_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userpurchase',
            index=models.Index(fields=['vcf_file'], name='purchase_vcf_file_idx'),
        ),
        migrations.AddIndex(
            model_name='userpurchase',
            index=models.Index(fields=['is_verified', 'is_active'], name='purchase_verified_active_idx'),
        ),
    ]
